name: Go Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Install dependencies
      run: go mod download
      working-directory: ./api/go-gin-api
    
    - name: Run tests
      run: go test ./... -v -coverprofile=coverage.out
      working-directory: ./api/go-gin-api
    
    - name: Generate coverage report
      run: go tool cover -html=coverage.out -o coverage.html
      working-directory: ./api/go-gin-api
    
    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: api/go-gin-api/coverage.html

