source 'https://rubygems.org'

ruby '~> 3.2.0'

gem 'sinatra', '~> 4.0'
gem 'sinatra-cross_origin', '~> 0.4'
gem 'puma', '~> 6.4'
gem 'json', '~> 2.7'
gem 'rackup', '~> 2.1'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
  gem 'simplecov', '~> 0.22', require: false
end

