version: '3.8'

services:
  spicy-todo-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spicy-todo-api
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_RELOAD=false
    volumes:
      # Mount the application code for development (optional)
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - spicy-todo-network

networks:
  spicy-todo-network:
    driver: bridge
